title: Juan Felipe Manrique Otálora
description: Campaign Operations | Audience & Performance Thinking | Process Design | Team Development
  
theme: jekyll-theme-minimal
show_downloads: false
logo: /Profile.JPG
